### ISSUE TITLE
Cookies/Persistence

### ISSUE THREAD

**Issue by Speuce** [Speuce/JAMCo#102]
Make it such that after logging in, a cookie/localstorage item is stored with the user credential such that the user does not need to log in after refresh.

**Comment by jaredwebber** [comment]
- Update user `last_login` field on login (`query.get_or_create_user`)
- Create encrypt/decrypt backend functions
  - Use base (static) backend key
  - Encrypt: (Called by `business.get_or_create_user`)
    - Create hash `{ google_id, last_login }` with static key
    - Return hash
  - Decrypt: (create `account/authenticate` endpoint)
    - Reverse hash with static key
    - Validate `google_id` & `last_login` match a database user
    - Return User
- Return encrypted token in `get_or_create_user` (possibly instead of `created` flag?)
- In `MainView` check cookies for `auth_token`
  - If token exists, validate token using (new) `account/authenticate` endpoint
    - If User returned, populate `userData`, call `userSignedIn`
    - If `ValidationError (401)` exit
  - If token doesnt exist, or `account/authenticate` failed
    - Require OAuth authentication
    - Create `auth_token` with hash returned in from `get_or_create_user`
